services:
  postgres:
    image: postgres:15-alpine
    container_name: cloud-retail-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudretail
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  iam-service:
    build:
      context: ./services/iam-service
    container_name: iam-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgres://user:password@postgres:5432/iam_db
      - JWT_SECRET=supersecretkey
    depends_on:
      - postgres

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  product-service:
    build:
      context: ./services/product-service
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - AWS_REGION=us-east-1
      - TABLE_NAME=Products
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    depends_on:
      - dynamodb-local

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=postgres://user:password@postgres:5432/order_db
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - INVENTORY_SERVICE_URL=http://inventory-service:3004
    depends_on:
      - postgres

  inventory-service:
    build:
      context: ./services/inventory-service
    container_name: inventory-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DATABASE_URL=postgres://user:password@postgres:5432/inventory_db
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_IAM_API_URL=http://localhost:3001
        - VITE_PRODUCT_API_URL=http://localhost:3002
        - VITE_ORDER_API_URL=http://localhost:3003
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - iam-service
      - product-service
      - order-service
      - inventory-service

volumes:
  postgres_data:
